---
title: "Visualizing Income"
output: html_document
---

```{r setup, include=FALSE}
library(leaflet)
library(tigris)
library(acs)
library(dplyr)

knitr::opts_chunk$set(echo = TRUE)
```


```{r geo_data}
spatialdataIN <- tracts(state="IN", county=c("St. Joseph","Elkhart"), cb=TRUE)
spatialdataMI <- tracts(state="MI", county=c("Cass","Berrien"), cb=TRUE)
spatialSB <- rbind_tigris(spatialdataIN, spatialdataMI)

geoIN <- geo.make(state="IN", county=c("St. Joseph","Elkhart"), tract="*")
geoMI <- geo.make(state="MI", county=c("Cass","Berrien"), tract="*")
SBarea <- geoIN + geoMI
```


```{r census_income}
income <-acs.fetch(endyear = 2012, span = 5, geography = SBarea, table.number = "B19001", col.names = "pretty")
```

```{r prep_data}
above100K <- rowSums(income@estimate[,14:17])

income_df <- data.frame(paste0(str_pad(income@geography$state, 2, "left", pad="0"), 
                                 str_pad(income@geography$county, 3, "left", pad="0"), 
                                 str_pad(income@geography$tract, 6, "left", pad="0")), 
                          income@estimate,
                          above100K,
                          stringsAsFactors = FALSE)

#income_df <- select(income_df, c(1,2,19))
rownames(income_df)<-1:nrow(income_df)
names(income_df)[c(1,2,19)]<-c("GEOID", "total", "over_100")
income_df$percent <- 100*(income_df$over_100/income_df$total)
income_merged<- geo_join(spatialSB, income_df, "GEOID", "GEOID")
income_merged <- income_merged[income_merged$ALAND>0,]
```

```{r plot_prep}
popup <- paste0("GEOID: ", income_merged$GEOID, "<br>", "Percent of Households above $100k: ", round(income_merged$percent,2))
pal <- colorNumeric(
  palette = "YlGnBu",
  domain = income_merged$percent
)
```

```{r leaflet plot}
leaflet() %>%
  addProviderTiles("CartoDB.Positron") %>%
  addPolygons(data = income_merged, 
              fillColor = ~pal(percent), 
              color = "#b2aeae", # you need to use hex colors
              fillOpacity = 0.7, 
              weight = 1, 
              smoothFactor = 0.2,
              popup = popup) %>%
  addLegend(pal = pal, 
            values = income_merged$percent, 
            position = "bottomright", 
            title = "Percent of Households<br>above $100k",
            labFormat = labelFormat(suffix = "%"))
```

